### PR TITLE
coma separated stats

### PR DESCRIPTION
**Pull request by GreggKr**
wow this branch has a lot of spelling mistakes. fairly close to the same system as Rythm

### CODE REVIEW

**Comment by atiwiex** [comment]
I don't see the point in this. The command looks fine as it is

**Comment by GreggKr** [comment]
To better separate statistics. It's much easier to tell what the numbers are now, but it will help further down the line, @atiwiex.

**Comment by GreggKr** [comment]
+ now it's more like Rythm :D

**Comment by atiwiex** [comment]
Does this change anything visually in discord?

**Comment by GreggKr** [comment]
Yes. As the PR, branch, and commit name suggest, it separates the numbers present in the stats command embed to be comma separated.

**Comment by atiwiex** [comment]
I don't see the point in this.

**Comment by Repulser** [comment]
Great one! Im pretty sure `NumberFormat#format` supports ints / longs so you can remove the overhead of making them strings.

**Comment by GreggKr** [comment]
oops! over site

**Comment by GreggKr** [comment]
changed

**Pull request merged**
