### PR TITLE
Mute role automatically go to the top on creation.

### PR DESCRIPTION
**Pull request by KJP12**
Modified the code to move the mute role to the top, so it can mute more members.

### CODE REVIEW

**Comment by MattIPv4** [comment]
Not sure this pull will do much. If a user has a green tick send messages override on a channel, nothing can stop them. If a user doesn't have a green tick, a red cross can be at any position and work.

**Comment by Tidanium** [comment]
Could make it so that it notifies the one who set it up as to which channels have overrides that allow them to send messages and which roles have that override so they may fix it if they can.

**Comment by Repulser** [comment]
This also can be problematic for admins.... if the bot is above them it makes it so admins cannot ban users with the `Muted` role, i still think this should be up to the admins to change manually....

**Comment by Tidanium** [comment]
If that's the case, why not make it go right below the top-most role of the one who set it up?

**Comment by Repulser** [comment]
It still can cause problems, I believe the best way is changing the role position manually.

**Pull request closed without merging**
